{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hello-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hello-app.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }} 
  rules:
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}             
    {{- end }}
{{- end }}
